import Link from "next/link";

export const metadata = {
  title: "About Page",
  description: "Generated by MH",
};

const AboutLayout = ({ children }) => {
  return (
    <div>
      <nav className="mt-6">
        <ul className="flex gap-x-4">
          <li>
            <Link href="/about/mission">Mission</Link>
          </li>
          <li>|</li>
          <li>
            <Link href="/about/vision">Vision</Link>
          </li>
        </ul>
      </nav>
      {children}
    </div>
  );
};

export default AboutLayout;
