import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={roboto.className}>
        <nav>
          <ul className="flex gap-x-4">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>|</li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>|</li>
            <li>
              <Link href="/blogs">Blogs</Link>
            </li>
            <li>|</li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
